// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ8ECNxiRVtu1gNtcpakXn2h7UtOt9nuw',
    appId: '1:845126007151:android:07810c70241f904980909a',
    messagingSenderId: '845126007151',
    projectId: 'training-6-instaclone',
    storageBucket: 'training-6-instaclone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9UPfew_jQD0UZ2zyHpnJumkR-4mPM-ZU',
    appId: '1:845126007151:ios:155810535b93cc4780909a',
    messagingSenderId: '845126007151',
    projectId: 'training-6-instaclone',
    storageBucket: 'training-6-instaclone.appspot.com',
    iosClientId: '845126007151-gcjr2og4h3c83l0bo319dpeq8jjelgf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.training6Instaclone',
  );
}
